export const INCREMENT_COUNTER = 'homepage/INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'homepage/DECREMENT_COUNTER';
export const RESET_COUNTER_LAUNCHED = 'homepage/RESET_COUNTER_LAUNCHED';
export const RESET_COUNTER_SUCCESS = 'homepage/RESET_COUNTER_SUCCESS';
export const RESET_COUNTER_FAILURE = 'homepage/RESET_COUNTER_FAILURE';
